Rename and segment avro_client functionality
NYPL/python-utils pull request #29
Opened 2024-07-02 14:16 UTC by fatimarahman

To service [DE-101](https://newyorkpubliclibrary.atlassian.net/browse/DE-101) (Python rewrite of Firehose Avro decoding), I have made the following changes:
- Split Avro decoding and encoding capabilities into separate classes (AvroDecoder and AvroEncoder)
- Made retrieving JSON schemas a publicly accessible functionality
- Added ability to decode base64 records to AvroDecoder (+ additional tests to make sure this works)

2024-07-02 14:21 UTC, fatimarahman commented
Are we still using `flake8` as the linter here? Or should I switch it to `black` in the Makefile?

2024-07-02 16:57 UTC, fatimarahman commented
Fixed it! @aaronfriedman6

2024-07-03 20:09 UTC, aaronfriedman6 reviewed
Looks great -- just a couple small changes plus one more function and I think it'll be good to go!

2024-07-03 20:09 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +class AvroEncoder(AvroClient):
Was the rational for splitting the Encoder/Decoder into two classes that we're only ever either encoding or decoding but never both at once? I'm not against this setup just curious why you picked it over keeping everything in one class.

2024-07-08 16:51 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
> +    def _decode_base64(self, record):
Yeah I'm going to remove this because I realize this is totally unnecessary lol (I initially thought the Kinesis records were encoded in b64)

2024-07-08 16:54 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
> +class AvroEncoder(AvroClient):
Correct me if I'm wrong, but I don't think the decoder code is used anywhere within NYPL, at least in the public repos. For our use case (the Firehose transformer), we only need access to the decoding functionality. In addition, the original AvroEncoder felt like a misnomer and it was a pretty large class that I felt could be broken down. Totally down to revert these changes tho, just thought it'd be nice for the future!

2024-07-08 16:56 UTC, fatimarahman commented on pyproject.toml
> +addopts = "-ra -q"
[-ra](https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags) displays extra test summary info for each test (i.e. displays test name and things like whether expected output matches actual output, etc). Can remove it if need be!

2024-07-09 15:07 UTC, aaronfriedman6 commented on pyproject.toml
> +addopts = "-ra -q"
No that's great I was just curious!

2024-07-09 15:24 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
Do we still need this? What is the primary input type if this were used in the wild? Disambiguating between these two types in this way can also be tricky -- I believe `b64encode` produces a base64 byte string for instance.

2024-07-09 15:24 UTC, aaronfriedman6 commented on tests/test_avro_client.py
> +        # assert test_avro_decoder_instance.schema == _TEST_SCHEMA['data'][
Add back

2024-07-09 15:24 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
>      def _decode_binary(self, record):
Now that there's no `_decode_base64` can this be joined into the `decode_record` function?

2024-07-09 15:24 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        Returns a list of strings where each string is an decoded record.
nit: grammar

2024-07-09 15:24 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +            'Encoding ({num_rec}) records using {schema} schema'.format(
nit: Decoding

2024-07-09 15:26 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +class AvroEncoder(AvroClient):
Yep until now the decode functionality was just for testing that the encoder worked. And yeah that all makes sense -- no need to change it!

2024-07-09 15:39 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
>      def _decode_binary(self, record):
Done!

2024-07-09 15:42 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
This one is weird because from my understanding, a lot of our record data aren't actually in binary: https://github.com/NYPL/firehose-avro-to-json-transformer/blob/main/test/stubs/records.json

This was the only way I could even translate the record data strings into something human readable. The original RecordProcessor in the Firehose code does something similar

2024-07-10 20:22 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
hmmm ignoring the tests the transformer is presumably only actually receiving one type (either binary or a base64 string). I think we should figure out what that type is and only handle it without handling the other type.

2024-07-10 20:24 UTC, aaronfriedman6 commented
I think you accidentally switched back to using the `black` formatter

2024-07-11 16:31 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
I've confirmed the transformer will receive a base64 string and NOT binary

2024-07-11 17:32 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
Ah gotcha! How did you figure that out? I think I massively overthought this then hahah

2024-07-11 17:39 UTC, fatimarahman commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
Bc that's what I initially thought too but when I decode the binary to text I get something like this:
![Screenshot 2024-07-11 at 1 38 36 PM](https://github.com/NYPL/python-utils/assets/53092247/f0ef8b38-ed20-4a53-a526-c9d995e66b26)

2024-07-11 18:15 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        bytes_input = base64.b64decode(record) if (
I made a no-op Python function to read in records and attached it to one of the QA Kinesis firehoses as the transformer. I believe you might not be able to decode the binary directly to UTF because it's serialized with an Avro schema still.

2024-07-15 18:53 UTC, aaronfriedman6 requested changes
In addition to the comments, please reformat to flake8 and update the CHANGELOG -- then this should be good to go!

2024-07-15 18:53 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        Decodes a single record represented either as a byte or
nit: remove the byte part now that it should only accept hex strings

2024-07-15 18:53 UTC, aaronfriedman6 commented on tests/test_avro_client.py
> +        TEST_ENCODED_RECORD = b'\xf6\x01\x02\x04aa'
The input to the decode_record function should be a hex string

2024-07-17 13:34 UTC, fatimarahman commented on tests/test_avro_client.py
> +        TEST_ENCODED_RECORD = b'\xf6\x01\x02\x04aa'
I pulled the encoded_record input from the results of [this test](https://github.com/NYPL/python-utils/blob/f9c5b43206a43754859995f38750cdc5296ef0df/tests/test_avro_client.py#L74). Should it be otherwise?

2024-07-17 13:35 UTC, fatimarahman commented on tests/test_avro_client.py
> +        TEST_ENCODED_RECORD = b'\xf6\x01\x02\x04aa'
Also from my understanding the input should be a bytes-type object, as per the [original code](https://github.com/NYPL/python-utils/blob/07927f5ce79c93dd08fdf46a54840343e723de44/src/nypl_py_utils/classes/avro_encoder.py#L77).

2024-07-17 14:00 UTC, aaronfriedman6 commented on tests/test_avro_client.py
> +        TEST_ENCODED_RECORD = b'\xf6\x01\x02\x04aa'
Resolved offline -- the function will take in a bytes-type object

2024-07-17 14:02 UTC, aaronfriedman6 approved these changes

2024-07-17 14:02 UTC, aaronfriedman6 commented on src/nypl_py_utils/classes/avro_client.py
> +        Decodes a single record represented using the given Avro schema.
Here and below: specify in the method description that the input record(s) should be bytes

2024-07-17 14:22 UTC, aaronfriedman6 approved these changes

2024-07-17 14:23 UTC, merged